# Homepage
homepage:
    path: /
    defaults: { _controller: Pages }

# Static pages
static:
    path: /pages/{page}
    defaults: { _controller: Pages, _action: render }

# Index for a podcast
podcast_index:
    path: /{podcast}
    defaults: { _controller: Podcast, _action: index }

# Index for a episode
episode_index:
    path: /{podcast}/{episode}
    defaults: { _controller: Episode, _action: index }